# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.21

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/lor_louis/Documents/Projects/C++/toaster

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/lor_louis/Documents/Projects/C++/toaster

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lor_louis/Documents/Projects/C++/toaster/CMakeFiles /home/lor_louis/Documents/Projects/C++/toaster//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lor_louis/Documents/Projects/C++/toaster/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named upload-toaster

# Build rule for target.
upload-toaster: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 upload-toaster
.PHONY : upload-toaster

# fast build rule for target.
upload-toaster/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/upload-toaster.dir/build.make CMakeFiles/upload-toaster.dir/build
.PHONY : upload-toaster/fast

#=============================================================================
# Target rules for targets named _arduino_lib_LiquidCrystal

# Build rule for target.
_arduino_lib_LiquidCrystal: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 _arduino_lib_LiquidCrystal
.PHONY : _arduino_lib_LiquidCrystal

# fast build rule for target.
_arduino_lib_LiquidCrystal/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_arduino_lib_LiquidCrystal.dir/build.make CMakeFiles/_arduino_lib_LiquidCrystal.dir/build
.PHONY : _arduino_lib_LiquidCrystal/fast

#=============================================================================
# Target rules for targets named _arduino_lib_Encoder

# Build rule for target.
_arduino_lib_Encoder: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 _arduino_lib_Encoder
.PHONY : _arduino_lib_Encoder

# fast build rule for target.
_arduino_lib_Encoder/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_arduino_lib_Encoder.dir/build.make CMakeFiles/_arduino_lib_Encoder.dir/build
.PHONY : _arduino_lib_Encoder/fast

#=============================================================================
# Target rules for targets named _arduino_lib_EEPROM

# Build rule for target.
_arduino_lib_EEPROM: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 _arduino_lib_EEPROM
.PHONY : _arduino_lib_EEPROM

# fast build rule for target.
_arduino_lib_EEPROM/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_arduino_lib_EEPROM.dir/build.make CMakeFiles/_arduino_lib_EEPROM.dir/build
.PHONY : _arduino_lib_EEPROM/fast

#=============================================================================
# Target rules for targets named _arduino_lib_core

# Build rule for target.
_arduino_lib_core: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 _arduino_lib_core
.PHONY : _arduino_lib_core

# fast build rule for target.
_arduino_lib_core/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_arduino_lib_core.dir/build.make CMakeFiles/_arduino_lib_core.dir/build
.PHONY : _arduino_lib_core/fast

#=============================================================================
# Target rules for targets named toaster

# Build rule for target.
toaster: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 toaster
.PHONY : toaster

# fast build rule for target.
toaster/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/toaster.dir/build.make CMakeFiles/toaster.dir/build
.PHONY : toaster/fast

_arduino_lib_EEPROM_dummy.o: _arduino_lib_EEPROM_dummy.cpp.o
.PHONY : _arduino_lib_EEPROM_dummy.o

# target to build an object file
_arduino_lib_EEPROM_dummy.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_arduino_lib_EEPROM.dir/build.make CMakeFiles/_arduino_lib_EEPROM.dir/_arduino_lib_EEPROM_dummy.cpp.o
.PHONY : _arduino_lib_EEPROM_dummy.cpp.o

_arduino_lib_EEPROM_dummy.i: _arduino_lib_EEPROM_dummy.cpp.i
.PHONY : _arduino_lib_EEPROM_dummy.i

# target to preprocess a source file
_arduino_lib_EEPROM_dummy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_arduino_lib_EEPROM.dir/build.make CMakeFiles/_arduino_lib_EEPROM.dir/_arduino_lib_EEPROM_dummy.cpp.i
.PHONY : _arduino_lib_EEPROM_dummy.cpp.i

_arduino_lib_EEPROM_dummy.s: _arduino_lib_EEPROM_dummy.cpp.s
.PHONY : _arduino_lib_EEPROM_dummy.s

# target to generate assembly for a file
_arduino_lib_EEPROM_dummy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_arduino_lib_EEPROM.dir/build.make CMakeFiles/_arduino_lib_EEPROM.dir/_arduino_lib_EEPROM_dummy.cpp.s
.PHONY : _arduino_lib_EEPROM_dummy.cpp.s

home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/CDC.o: home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/CDC.cpp.o
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/CDC.o

# target to build an object file
home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/CDC.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_arduino_lib_core.dir/build.make CMakeFiles/_arduino_lib_core.dir/home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/CDC.cpp.o
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/CDC.cpp.o

home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/CDC.i: home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/CDC.cpp.i
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/CDC.i

# target to preprocess a source file
home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/CDC.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_arduino_lib_core.dir/build.make CMakeFiles/_arduino_lib_core.dir/home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/CDC.cpp.i
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/CDC.cpp.i

home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/CDC.s: home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/CDC.cpp.s
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/CDC.s

# target to generate assembly for a file
home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/CDC.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_arduino_lib_core.dir/build.make CMakeFiles/_arduino_lib_core.dir/home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/CDC.cpp.s
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/CDC.cpp.s

home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/HardwareSerial.o: home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/HardwareSerial.cpp.o
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/HardwareSerial.o

# target to build an object file
home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/HardwareSerial.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_arduino_lib_core.dir/build.make CMakeFiles/_arduino_lib_core.dir/home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/HardwareSerial.cpp.o
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/HardwareSerial.cpp.o

home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/HardwareSerial.i: home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/HardwareSerial.cpp.i
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/HardwareSerial.i

# target to preprocess a source file
home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/HardwareSerial.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_arduino_lib_core.dir/build.make CMakeFiles/_arduino_lib_core.dir/home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/HardwareSerial.cpp.i
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/HardwareSerial.cpp.i

home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/HardwareSerial.s: home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/HardwareSerial.cpp.s
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/HardwareSerial.s

# target to generate assembly for a file
home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/HardwareSerial.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_arduino_lib_core.dir/build.make CMakeFiles/_arduino_lib_core.dir/home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/HardwareSerial.cpp.s
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/HardwareSerial.cpp.s

home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/HardwareSerial0.o: home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/HardwareSerial0.cpp.o
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/HardwareSerial0.o

# target to build an object file
home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/HardwareSerial0.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_arduino_lib_core.dir/build.make CMakeFiles/_arduino_lib_core.dir/home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/HardwareSerial0.cpp.o
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/HardwareSerial0.cpp.o

home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/HardwareSerial0.i: home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/HardwareSerial0.cpp.i
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/HardwareSerial0.i

# target to preprocess a source file
home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/HardwareSerial0.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_arduino_lib_core.dir/build.make CMakeFiles/_arduino_lib_core.dir/home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/HardwareSerial0.cpp.i
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/HardwareSerial0.cpp.i

home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/HardwareSerial0.s: home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/HardwareSerial0.cpp.s
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/HardwareSerial0.s

# target to generate assembly for a file
home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/HardwareSerial0.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_arduino_lib_core.dir/build.make CMakeFiles/_arduino_lib_core.dir/home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/HardwareSerial0.cpp.s
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/HardwareSerial0.cpp.s

home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/HardwareSerial1.o: home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/HardwareSerial1.cpp.o
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/HardwareSerial1.o

# target to build an object file
home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/HardwareSerial1.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_arduino_lib_core.dir/build.make CMakeFiles/_arduino_lib_core.dir/home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/HardwareSerial1.cpp.o
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/HardwareSerial1.cpp.o

home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/HardwareSerial1.i: home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/HardwareSerial1.cpp.i
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/HardwareSerial1.i

# target to preprocess a source file
home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/HardwareSerial1.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_arduino_lib_core.dir/build.make CMakeFiles/_arduino_lib_core.dir/home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/HardwareSerial1.cpp.i
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/HardwareSerial1.cpp.i

home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/HardwareSerial1.s: home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/HardwareSerial1.cpp.s
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/HardwareSerial1.s

# target to generate assembly for a file
home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/HardwareSerial1.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_arduino_lib_core.dir/build.make CMakeFiles/_arduino_lib_core.dir/home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/HardwareSerial1.cpp.s
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/HardwareSerial1.cpp.s

home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/HardwareSerial2.o: home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/HardwareSerial2.cpp.o
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/HardwareSerial2.o

# target to build an object file
home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/HardwareSerial2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_arduino_lib_core.dir/build.make CMakeFiles/_arduino_lib_core.dir/home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/HardwareSerial2.cpp.o
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/HardwareSerial2.cpp.o

home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/HardwareSerial2.i: home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/HardwareSerial2.cpp.i
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/HardwareSerial2.i

# target to preprocess a source file
home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/HardwareSerial2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_arduino_lib_core.dir/build.make CMakeFiles/_arduino_lib_core.dir/home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/HardwareSerial2.cpp.i
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/HardwareSerial2.cpp.i

home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/HardwareSerial2.s: home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/HardwareSerial2.cpp.s
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/HardwareSerial2.s

# target to generate assembly for a file
home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/HardwareSerial2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_arduino_lib_core.dir/build.make CMakeFiles/_arduino_lib_core.dir/home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/HardwareSerial2.cpp.s
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/HardwareSerial2.cpp.s

home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/HardwareSerial3.o: home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/HardwareSerial3.cpp.o
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/HardwareSerial3.o

# target to build an object file
home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/HardwareSerial3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_arduino_lib_core.dir/build.make CMakeFiles/_arduino_lib_core.dir/home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/HardwareSerial3.cpp.o
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/HardwareSerial3.cpp.o

home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/HardwareSerial3.i: home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/HardwareSerial3.cpp.i
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/HardwareSerial3.i

# target to preprocess a source file
home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/HardwareSerial3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_arduino_lib_core.dir/build.make CMakeFiles/_arduino_lib_core.dir/home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/HardwareSerial3.cpp.i
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/HardwareSerial3.cpp.i

home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/HardwareSerial3.s: home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/HardwareSerial3.cpp.s
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/HardwareSerial3.s

# target to generate assembly for a file
home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/HardwareSerial3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_arduino_lib_core.dir/build.make CMakeFiles/_arduino_lib_core.dir/home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/HardwareSerial3.cpp.s
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/HardwareSerial3.cpp.s

home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/IPAddress.o: home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/IPAddress.cpp.o
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/IPAddress.o

# target to build an object file
home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/IPAddress.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_arduino_lib_core.dir/build.make CMakeFiles/_arduino_lib_core.dir/home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/IPAddress.cpp.o
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/IPAddress.cpp.o

home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/IPAddress.i: home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/IPAddress.cpp.i
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/IPAddress.i

# target to preprocess a source file
home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/IPAddress.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_arduino_lib_core.dir/build.make CMakeFiles/_arduino_lib_core.dir/home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/IPAddress.cpp.i
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/IPAddress.cpp.i

home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/IPAddress.s: home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/IPAddress.cpp.s
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/IPAddress.s

# target to generate assembly for a file
home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/IPAddress.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_arduino_lib_core.dir/build.make CMakeFiles/_arduino_lib_core.dir/home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/IPAddress.cpp.s
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/IPAddress.cpp.s

home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/PluggableUSB.o: home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/PluggableUSB.cpp.o
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/PluggableUSB.o

# target to build an object file
home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/PluggableUSB.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_arduino_lib_core.dir/build.make CMakeFiles/_arduino_lib_core.dir/home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/PluggableUSB.cpp.o
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/PluggableUSB.cpp.o

home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/PluggableUSB.i: home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/PluggableUSB.cpp.i
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/PluggableUSB.i

# target to preprocess a source file
home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/PluggableUSB.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_arduino_lib_core.dir/build.make CMakeFiles/_arduino_lib_core.dir/home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/PluggableUSB.cpp.i
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/PluggableUSB.cpp.i

home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/PluggableUSB.s: home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/PluggableUSB.cpp.s
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/PluggableUSB.s

# target to generate assembly for a file
home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/PluggableUSB.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_arduino_lib_core.dir/build.make CMakeFiles/_arduino_lib_core.dir/home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/PluggableUSB.cpp.s
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/PluggableUSB.cpp.s

home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/Print.o: home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/Print.cpp.o
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/Print.o

# target to build an object file
home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/Print.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_arduino_lib_core.dir/build.make CMakeFiles/_arduino_lib_core.dir/home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/Print.cpp.o
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/Print.cpp.o

home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/Print.i: home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/Print.cpp.i
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/Print.i

# target to preprocess a source file
home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/Print.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_arduino_lib_core.dir/build.make CMakeFiles/_arduino_lib_core.dir/home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/Print.cpp.i
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/Print.cpp.i

home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/Print.s: home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/Print.cpp.s
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/Print.s

# target to generate assembly for a file
home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/Print.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_arduino_lib_core.dir/build.make CMakeFiles/_arduino_lib_core.dir/home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/Print.cpp.s
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/Print.cpp.s

home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/Stream.o: home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/Stream.cpp.o
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/Stream.o

# target to build an object file
home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/Stream.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_arduino_lib_core.dir/build.make CMakeFiles/_arduino_lib_core.dir/home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/Stream.cpp.o
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/Stream.cpp.o

home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/Stream.i: home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/Stream.cpp.i
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/Stream.i

# target to preprocess a source file
home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/Stream.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_arduino_lib_core.dir/build.make CMakeFiles/_arduino_lib_core.dir/home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/Stream.cpp.i
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/Stream.cpp.i

home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/Stream.s: home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/Stream.cpp.s
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/Stream.s

# target to generate assembly for a file
home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/Stream.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_arduino_lib_core.dir/build.make CMakeFiles/_arduino_lib_core.dir/home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/Stream.cpp.s
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/Stream.cpp.s

home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/Tone.o: home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/Tone.cpp.o
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/Tone.o

# target to build an object file
home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/Tone.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_arduino_lib_core.dir/build.make CMakeFiles/_arduino_lib_core.dir/home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/Tone.cpp.o
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/Tone.cpp.o

home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/Tone.i: home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/Tone.cpp.i
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/Tone.i

# target to preprocess a source file
home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/Tone.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_arduino_lib_core.dir/build.make CMakeFiles/_arduino_lib_core.dir/home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/Tone.cpp.i
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/Tone.cpp.i

home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/Tone.s: home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/Tone.cpp.s
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/Tone.s

# target to generate assembly for a file
home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/Tone.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_arduino_lib_core.dir/build.make CMakeFiles/_arduino_lib_core.dir/home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/Tone.cpp.s
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/Tone.cpp.s

home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/USBCore.o: home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/USBCore.cpp.o
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/USBCore.o

# target to build an object file
home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/USBCore.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_arduino_lib_core.dir/build.make CMakeFiles/_arduino_lib_core.dir/home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/USBCore.cpp.o
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/USBCore.cpp.o

home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/USBCore.i: home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/USBCore.cpp.i
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/USBCore.i

# target to preprocess a source file
home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/USBCore.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_arduino_lib_core.dir/build.make CMakeFiles/_arduino_lib_core.dir/home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/USBCore.cpp.i
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/USBCore.cpp.i

home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/USBCore.s: home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/USBCore.cpp.s
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/USBCore.s

# target to generate assembly for a file
home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/USBCore.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_arduino_lib_core.dir/build.make CMakeFiles/_arduino_lib_core.dir/home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/USBCore.cpp.s
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/USBCore.cpp.s

home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/WInterrupts.o: home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/WInterrupts.c.o
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/WInterrupts.o

# target to build an object file
home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/WInterrupts.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_arduino_lib_core.dir/build.make CMakeFiles/_arduino_lib_core.dir/home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/WInterrupts.c.o
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/WInterrupts.c.o

home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/WInterrupts.i: home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/WInterrupts.c.i
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/WInterrupts.i

# target to preprocess a source file
home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/WInterrupts.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_arduino_lib_core.dir/build.make CMakeFiles/_arduino_lib_core.dir/home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/WInterrupts.c.i
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/WInterrupts.c.i

home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/WInterrupts.s: home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/WInterrupts.c.s
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/WInterrupts.s

# target to generate assembly for a file
home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/WInterrupts.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_arduino_lib_core.dir/build.make CMakeFiles/_arduino_lib_core.dir/home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/WInterrupts.c.s
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/WInterrupts.c.s

home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/WMath.o: home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/WMath.cpp.o
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/WMath.o

# target to build an object file
home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/WMath.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_arduino_lib_core.dir/build.make CMakeFiles/_arduino_lib_core.dir/home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/WMath.cpp.o
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/WMath.cpp.o

home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/WMath.i: home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/WMath.cpp.i
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/WMath.i

# target to preprocess a source file
home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/WMath.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_arduino_lib_core.dir/build.make CMakeFiles/_arduino_lib_core.dir/home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/WMath.cpp.i
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/WMath.cpp.i

home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/WMath.s: home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/WMath.cpp.s
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/WMath.s

# target to generate assembly for a file
home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/WMath.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_arduino_lib_core.dir/build.make CMakeFiles/_arduino_lib_core.dir/home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/WMath.cpp.s
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/WMath.cpp.s

home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/WString.o: home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/WString.cpp.o
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/WString.o

# target to build an object file
home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/WString.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_arduino_lib_core.dir/build.make CMakeFiles/_arduino_lib_core.dir/home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/WString.cpp.o
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/WString.cpp.o

home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/WString.i: home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/WString.cpp.i
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/WString.i

# target to preprocess a source file
home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/WString.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_arduino_lib_core.dir/build.make CMakeFiles/_arduino_lib_core.dir/home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/WString.cpp.i
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/WString.cpp.i

home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/WString.s: home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/WString.cpp.s
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/WString.s

# target to generate assembly for a file
home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/WString.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_arduino_lib_core.dir/build.make CMakeFiles/_arduino_lib_core.dir/home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/WString.cpp.s
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/WString.cpp.s

home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/abi.o: home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/abi.cpp.o
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/abi.o

# target to build an object file
home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/abi.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_arduino_lib_core.dir/build.make CMakeFiles/_arduino_lib_core.dir/home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/abi.cpp.o
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/abi.cpp.o

home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/abi.i: home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/abi.cpp.i
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/abi.i

# target to preprocess a source file
home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/abi.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_arduino_lib_core.dir/build.make CMakeFiles/_arduino_lib_core.dir/home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/abi.cpp.i
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/abi.cpp.i

home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/abi.s: home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/abi.cpp.s
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/abi.s

# target to generate assembly for a file
home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/abi.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_arduino_lib_core.dir/build.make CMakeFiles/_arduino_lib_core.dir/home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/abi.cpp.s
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/abi.cpp.s

home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/hooks.o: home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/hooks.c.o
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/hooks.o

# target to build an object file
home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/hooks.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_arduino_lib_core.dir/build.make CMakeFiles/_arduino_lib_core.dir/home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/hooks.c.o
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/hooks.c.o

home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/hooks.i: home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/hooks.c.i
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/hooks.i

# target to preprocess a source file
home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/hooks.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_arduino_lib_core.dir/build.make CMakeFiles/_arduino_lib_core.dir/home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/hooks.c.i
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/hooks.c.i

home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/hooks.s: home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/hooks.c.s
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/hooks.s

# target to generate assembly for a file
home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/hooks.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_arduino_lib_core.dir/build.make CMakeFiles/_arduino_lib_core.dir/home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/hooks.c.s
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/hooks.c.s

home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/main.o: home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/main.cpp.o
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/main.o

# target to build an object file
home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_arduino_lib_core.dir/build.make CMakeFiles/_arduino_lib_core.dir/home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/main.cpp.o
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/main.cpp.o

home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/main.i: home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/main.cpp.i
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/main.i

# target to preprocess a source file
home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_arduino_lib_core.dir/build.make CMakeFiles/_arduino_lib_core.dir/home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/main.cpp.i
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/main.cpp.i

home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/main.s: home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/main.cpp.s
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/main.s

# target to generate assembly for a file
home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_arduino_lib_core.dir/build.make CMakeFiles/_arduino_lib_core.dir/home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/main.cpp.s
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/main.cpp.s

home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/new.o: home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/new.cpp.o
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/new.o

# target to build an object file
home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/new.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_arduino_lib_core.dir/build.make CMakeFiles/_arduino_lib_core.dir/home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/new.cpp.o
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/new.cpp.o

home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/new.i: home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/new.cpp.i
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/new.i

# target to preprocess a source file
home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/new.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_arduino_lib_core.dir/build.make CMakeFiles/_arduino_lib_core.dir/home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/new.cpp.i
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/new.cpp.i

home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/new.s: home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/new.cpp.s
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/new.s

# target to generate assembly for a file
home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/new.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_arduino_lib_core.dir/build.make CMakeFiles/_arduino_lib_core.dir/home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/new.cpp.s
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/new.cpp.s

home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring.o: home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring.c.o
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring.o

# target to build an object file
home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_arduino_lib_core.dir/build.make CMakeFiles/_arduino_lib_core.dir/home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring.c.o
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring.c.o

home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring.i: home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring.c.i
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring.i

# target to preprocess a source file
home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_arduino_lib_core.dir/build.make CMakeFiles/_arduino_lib_core.dir/home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring.c.i
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring.c.i

home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring.s: home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring.c.s
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring.s

# target to generate assembly for a file
home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_arduino_lib_core.dir/build.make CMakeFiles/_arduino_lib_core.dir/home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring.c.s
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring.c.s

home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring_analog.o: home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring_analog.c.o
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring_analog.o

# target to build an object file
home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring_analog.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_arduino_lib_core.dir/build.make CMakeFiles/_arduino_lib_core.dir/home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring_analog.c.o
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring_analog.c.o

home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring_analog.i: home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring_analog.c.i
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring_analog.i

# target to preprocess a source file
home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring_analog.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_arduino_lib_core.dir/build.make CMakeFiles/_arduino_lib_core.dir/home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring_analog.c.i
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring_analog.c.i

home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring_analog.s: home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring_analog.c.s
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring_analog.s

# target to generate assembly for a file
home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring_analog.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_arduino_lib_core.dir/build.make CMakeFiles/_arduino_lib_core.dir/home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring_analog.c.s
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring_analog.c.s

home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring_digital.o: home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring_digital.c.o
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring_digital.o

# target to build an object file
home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring_digital.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_arduino_lib_core.dir/build.make CMakeFiles/_arduino_lib_core.dir/home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring_digital.c.o
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring_digital.c.o

home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring_digital.i: home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring_digital.c.i
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring_digital.i

# target to preprocess a source file
home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring_digital.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_arduino_lib_core.dir/build.make CMakeFiles/_arduino_lib_core.dir/home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring_digital.c.i
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring_digital.c.i

home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring_digital.s: home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring_digital.c.s
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring_digital.s

# target to generate assembly for a file
home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring_digital.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_arduino_lib_core.dir/build.make CMakeFiles/_arduino_lib_core.dir/home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring_digital.c.s
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring_digital.c.s

home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring_pulse.obj: home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring_pulse.S.obj
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring_pulse.obj

# target to build an object file
home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring_pulse.S.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_arduino_lib_core.dir/build.make CMakeFiles/_arduino_lib_core.dir/home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring_pulse.S.obj
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring_pulse.S.obj

home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring_pulse.o: home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring_pulse.c.o
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring_pulse.o

# target to build an object file
home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring_pulse.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_arduino_lib_core.dir/build.make CMakeFiles/_arduino_lib_core.dir/home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring_pulse.c.o
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring_pulse.c.o

home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring_pulse.i: home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring_pulse.c.i
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring_pulse.i

# target to preprocess a source file
home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring_pulse.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_arduino_lib_core.dir/build.make CMakeFiles/_arduino_lib_core.dir/home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring_pulse.c.i
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring_pulse.c.i

home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring_pulse.s: home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring_pulse.c.s
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring_pulse.s

# target to generate assembly for a file
home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring_pulse.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_arduino_lib_core.dir/build.make CMakeFiles/_arduino_lib_core.dir/home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring_pulse.c.s
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring_pulse.c.s

home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring_shift.o: home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring_shift.c.o
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring_shift.o

# target to build an object file
home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring_shift.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_arduino_lib_core.dir/build.make CMakeFiles/_arduino_lib_core.dir/home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring_shift.c.o
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring_shift.c.o

home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring_shift.i: home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring_shift.c.i
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring_shift.i

# target to preprocess a source file
home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring_shift.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_arduino_lib_core.dir/build.make CMakeFiles/_arduino_lib_core.dir/home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring_shift.c.i
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring_shift.c.i

home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring_shift.s: home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring_shift.c.s
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring_shift.s

# target to generate assembly for a file
home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring_shift.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_arduino_lib_core.dir/build.make CMakeFiles/_arduino_lib_core.dir/home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring_shift.c.s
.PHONY : home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring_shift.c.s

home/lor_louis/Arduino/libraries/Encoder/Encoder.o: home/lor_louis/Arduino/libraries/Encoder/Encoder.cpp.o
.PHONY : home/lor_louis/Arduino/libraries/Encoder/Encoder.o

# target to build an object file
home/lor_louis/Arduino/libraries/Encoder/Encoder.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_arduino_lib_Encoder.dir/build.make CMakeFiles/_arduino_lib_Encoder.dir/home/lor_louis/Arduino/libraries/Encoder/Encoder.cpp.o
.PHONY : home/lor_louis/Arduino/libraries/Encoder/Encoder.cpp.o

home/lor_louis/Arduino/libraries/Encoder/Encoder.i: home/lor_louis/Arduino/libraries/Encoder/Encoder.cpp.i
.PHONY : home/lor_louis/Arduino/libraries/Encoder/Encoder.i

# target to preprocess a source file
home/lor_louis/Arduino/libraries/Encoder/Encoder.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_arduino_lib_Encoder.dir/build.make CMakeFiles/_arduino_lib_Encoder.dir/home/lor_louis/Arduino/libraries/Encoder/Encoder.cpp.i
.PHONY : home/lor_louis/Arduino/libraries/Encoder/Encoder.cpp.i

home/lor_louis/Arduino/libraries/Encoder/Encoder.s: home/lor_louis/Arduino/libraries/Encoder/Encoder.cpp.s
.PHONY : home/lor_louis/Arduino/libraries/Encoder/Encoder.s

# target to generate assembly for a file
home/lor_louis/Arduino/libraries/Encoder/Encoder.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_arduino_lib_Encoder.dir/build.make CMakeFiles/_arduino_lib_Encoder.dir/home/lor_louis/Arduino/libraries/Encoder/Encoder.cpp.s
.PHONY : home/lor_louis/Arduino/libraries/Encoder/Encoder.cpp.s

toaster.o: toaster.cpp.o
.PHONY : toaster.o

# target to build an object file
toaster.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/toaster.dir/build.make CMakeFiles/toaster.dir/toaster.cpp.o
.PHONY : toaster.cpp.o

toaster.i: toaster.cpp.i
.PHONY : toaster.i

# target to preprocess a source file
toaster.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/toaster.dir/build.make CMakeFiles/toaster.dir/toaster.cpp.i
.PHONY : toaster.cpp.i

toaster.s: toaster.cpp.s
.PHONY : toaster.s

# target to generate assembly for a file
toaster.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/toaster.dir/build.make CMakeFiles/toaster.dir/toaster.cpp.s
.PHONY : toaster.cpp.s

usr/share/arduino/libraries/LiquidCrystal/src/LiquidCrystal.o: usr/share/arduino/libraries/LiquidCrystal/src/LiquidCrystal.cpp.o
.PHONY : usr/share/arduino/libraries/LiquidCrystal/src/LiquidCrystal.o

# target to build an object file
usr/share/arduino/libraries/LiquidCrystal/src/LiquidCrystal.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_arduino_lib_LiquidCrystal.dir/build.make CMakeFiles/_arduino_lib_LiquidCrystal.dir/usr/share/arduino/libraries/LiquidCrystal/src/LiquidCrystal.cpp.o
.PHONY : usr/share/arduino/libraries/LiquidCrystal/src/LiquidCrystal.cpp.o

usr/share/arduino/libraries/LiquidCrystal/src/LiquidCrystal.i: usr/share/arduino/libraries/LiquidCrystal/src/LiquidCrystal.cpp.i
.PHONY : usr/share/arduino/libraries/LiquidCrystal/src/LiquidCrystal.i

# target to preprocess a source file
usr/share/arduino/libraries/LiquidCrystal/src/LiquidCrystal.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_arduino_lib_LiquidCrystal.dir/build.make CMakeFiles/_arduino_lib_LiquidCrystal.dir/usr/share/arduino/libraries/LiquidCrystal/src/LiquidCrystal.cpp.i
.PHONY : usr/share/arduino/libraries/LiquidCrystal/src/LiquidCrystal.cpp.i

usr/share/arduino/libraries/LiquidCrystal/src/LiquidCrystal.s: usr/share/arduino/libraries/LiquidCrystal/src/LiquidCrystal.cpp.s
.PHONY : usr/share/arduino/libraries/LiquidCrystal/src/LiquidCrystal.s

# target to generate assembly for a file
usr/share/arduino/libraries/LiquidCrystal/src/LiquidCrystal.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_arduino_lib_LiquidCrystal.dir/build.make CMakeFiles/_arduino_lib_LiquidCrystal.dir/usr/share/arduino/libraries/LiquidCrystal/src/LiquidCrystal.cpp.s
.PHONY : usr/share/arduino/libraries/LiquidCrystal/src/LiquidCrystal.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... upload-toaster"
	@echo "... _arduino_lib_EEPROM"
	@echo "... _arduino_lib_Encoder"
	@echo "... _arduino_lib_LiquidCrystal"
	@echo "... _arduino_lib_core"
	@echo "... toaster"
	@echo "... _arduino_lib_EEPROM_dummy.o"
	@echo "... _arduino_lib_EEPROM_dummy.i"
	@echo "... _arduino_lib_EEPROM_dummy.s"
	@echo "... home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/CDC.o"
	@echo "... home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/CDC.i"
	@echo "... home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/CDC.s"
	@echo "... home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/HardwareSerial.o"
	@echo "... home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/HardwareSerial.i"
	@echo "... home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/HardwareSerial.s"
	@echo "... home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/HardwareSerial0.o"
	@echo "... home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/HardwareSerial0.i"
	@echo "... home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/HardwareSerial0.s"
	@echo "... home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/HardwareSerial1.o"
	@echo "... home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/HardwareSerial1.i"
	@echo "... home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/HardwareSerial1.s"
	@echo "... home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/HardwareSerial2.o"
	@echo "... home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/HardwareSerial2.i"
	@echo "... home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/HardwareSerial2.s"
	@echo "... home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/HardwareSerial3.o"
	@echo "... home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/HardwareSerial3.i"
	@echo "... home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/HardwareSerial3.s"
	@echo "... home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/IPAddress.o"
	@echo "... home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/IPAddress.i"
	@echo "... home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/IPAddress.s"
	@echo "... home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/PluggableUSB.o"
	@echo "... home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/PluggableUSB.i"
	@echo "... home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/PluggableUSB.s"
	@echo "... home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/Print.o"
	@echo "... home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/Print.i"
	@echo "... home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/Print.s"
	@echo "... home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/Stream.o"
	@echo "... home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/Stream.i"
	@echo "... home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/Stream.s"
	@echo "... home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/Tone.o"
	@echo "... home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/Tone.i"
	@echo "... home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/Tone.s"
	@echo "... home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/USBCore.o"
	@echo "... home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/USBCore.i"
	@echo "... home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/USBCore.s"
	@echo "... home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/WInterrupts.o"
	@echo "... home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/WInterrupts.i"
	@echo "... home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/WInterrupts.s"
	@echo "... home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/WMath.o"
	@echo "... home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/WMath.i"
	@echo "... home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/WMath.s"
	@echo "... home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/WString.o"
	@echo "... home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/WString.i"
	@echo "... home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/WString.s"
	@echo "... home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/abi.o"
	@echo "... home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/abi.i"
	@echo "... home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/abi.s"
	@echo "... home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/hooks.o"
	@echo "... home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/hooks.i"
	@echo "... home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/hooks.s"
	@echo "... home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/main.o"
	@echo "... home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/main.i"
	@echo "... home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/main.s"
	@echo "... home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/new.o"
	@echo "... home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/new.i"
	@echo "... home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/new.s"
	@echo "... home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring.o"
	@echo "... home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring.i"
	@echo "... home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring.s"
	@echo "... home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring_analog.o"
	@echo "... home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring_analog.i"
	@echo "... home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring_analog.s"
	@echo "... home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring_digital.o"
	@echo "... home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring_digital.i"
	@echo "... home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring_digital.s"
	@echo "... home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring_pulse.obj"
	@echo "... home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring_pulse.o"
	@echo "... home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring_pulse.i"
	@echo "... home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring_pulse.s"
	@echo "... home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring_shift.o"
	@echo "... home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring_shift.i"
	@echo "... home/lor_louis/.arduino15/packages/arduino/hardware/avr/1.8.3/cores/arduino/wiring_shift.s"
	@echo "... home/lor_louis/Arduino/libraries/Encoder/Encoder.o"
	@echo "... home/lor_louis/Arduino/libraries/Encoder/Encoder.i"
	@echo "... home/lor_louis/Arduino/libraries/Encoder/Encoder.s"
	@echo "... toaster.o"
	@echo "... toaster.i"
	@echo "... toaster.s"
	@echo "... usr/share/arduino/libraries/LiquidCrystal/src/LiquidCrystal.o"
	@echo "... usr/share/arduino/libraries/LiquidCrystal/src/LiquidCrystal.i"
	@echo "... usr/share/arduino/libraries/LiquidCrystal/src/LiquidCrystal.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

